apiVersion: v1
kind: Service
metadata:
  name: custom-ng-service
spec:
  selector:
    app: custom-ng
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 80
  type: LoadBalancer
